services:
  db:
    image: mysql:9.2.0
    restart: always
    environment:
      MYSQL_DATABASE: 'sbook_db'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  web:
    build: .
    command: bash -c "while ! nc -z db 3306; do sleep 1; done && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=sbook_db
      - DB_USER=mysql
      - DB_PASSWORD=mysql
      - DB_PORT=3306
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "8080:80"
    depends_on:
      - db
    links:
      - db
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

volumes:
  mysql_data: