version: '3.8'

services:
  db:
    image: mariadb:10.5.27
    restart: always
    environment:
      MYSQL_DATABASE: 'sbook_db'
      MYSQL_ROOT_PASSWORD: null
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  web:
    build: .
    command: bash -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

volumes:
  mysql_data:
